# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
CONSUMER_KEY: "n48RtYBJlhcFDb3g0aC7o2378"
CONSUMER_SECRET: "LG3NzN8b1R3GB1Fde2ip8Yr7CRyfxLkS66oyY5Wahi6W5v2RJ8"
APP_ID: "4834584"
APP_SECRET: "0hfXmolZP9ibdipT0ry8"
GOOGLE_CLIENT_ID: "523961363645-d5rqlns7rje2va8oj1uffiqi0i6noiqd.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "_bgEuvdKi9LEPDkTnkEEpZmi"
MANDRILL_USERNAME: "sky7hunder@gmail.com"
MANDRILL_APIKEY: "z6dx1g7PdIUKOFczrTlfQw"
