["bychara",
 "byk",
 "chernozhopyi",
 "dolboy'eb",
 "ebalnik",
 "ebalo",
 "ebalom sch'elkat",
 "gol",
 "mudack",
 "opizdenet",
 "osto'eblo",
 "ostokhuitel'no",
 "ot'ebis",
 "otmudohat",
 "otpizdit",
 "otsosi",
 "padlo",
 "pedik",
 "perdet",
 "petuh",
 "pidar gnoinyj",
 "pizda",
 "pizdato",
 "pizdatyi",
 "piz'det",
 "pizdetc",
 "pizdoi nakryt'sja",
 "pizd'uk",
 "piz`dyulina",
 "podi ku'evo",
 "poeben",
 "po'imat' na konchik",
 "po'iti posrat",
 "po khuy",
 "poluchit pizdy",
 "pososi moyu konfetku",
 "prissat",
 "proebat",
 "promudobl'adsksya pizdopro'ebina",
 "propezdoloch",
 "prosrat",
 "raspeezde,yi",
 "raspizdatyi",
 "raz'yebuy",
 "raz'yoba",
 "s'ebat'sya",
 "shalava",
 "styervo",
 "sukin syn",
 "svodit posrat",
 "svoloch",
 "trakhat'sya",
 "trimandoblydskiy pizdoproyob",
 "ubl'yudok",
 "uboy",
 "u'ebitsche",
 "vafl'a",
 "vafli lovit",
 "v pizdu",
 "vyperdysh",
 "vzdrochennyi",
 "yeb vas",
 "za'ebat",
 "zaebis",
 "zalupa",
 "zalupat",
 "zasranetc",
 "zassat",
 "zlo'ebuchy",
 "бздёнок",
 "блядки",
 "блядовать",
 "блядство",
 "блядь",
 "бугор",
 "в пизду",
 "встать раком",
 "выёбываться",
 "гандон",
 "говно",
 "говнюк",
 "голый",
 "дать пизды",
 "дерьмо",
 "дрочить",
 "другой дразнится",
 "ёбарь",
 "ебать",
 "ебать-к,опать",
 "ебло",
 "ебнуть",
 "ёб твою мать",
 "жопа",
 "жополиз",
 "играть на кожаной флейте",
 "измудохать",
 "дрочит",
 "обоссать",
 "лысого в гонять",
 "малофя",
 "манда",
 "мандавошка",
 "мент",
 "муда",
 "мудило",
 "мудозмон",
 "наебать",
 "наебениться",
 "наебнуться",
 "на хуй",
 "на хую вертеть",
 "на хуя",
 "нахуячиться",
 "невебенный",
 "не ебет",
 "ни за хуй собачу",
 "ни хуя",
 "обоссаться",
 "ебётся",
 "опесдол",
 "охуеть",
 "охуйтельно",
 "секс",
 "сиски",
 "спиздить",
 "срать",
 "ссать",
 "траxать",
 "фига",
 "хапать",
 "хер с ней",
 "хер с ним",
 "хохол",
 "хрен",
 "хуёво",
 "хуёвый",
 "хуем груши околачивать",
 "хуеплет",
 "хуило",
 "хуиней страдать",
 "хуиня",
 "хуй",
 "хуйнуть",
 "хуй пинать" ]